### PR TITLE
Added ability to set `serialNumber` in Homebridge config (in UI also)

### PR DESCRIPTION
**Pull request by iSteve-O**
It was bothering me to have N/A in the Serial Number spot, so I added the ability to specify one. You just need to increase the version number to push this update. It is tested working.

### CODE REVIEW

**Comment by electroflame** [comment]
Hey @iSteve-O 
This looks good to me -- thanks for the PR!  I've got a few issues I'd like to see resolved before merging, though:

1. I do think the default of "N/A" should be kept, as DEFAULT SN is not as descriptive/factual.  Technically, if you don't supply a serial number, it would be "not available", and I suspect most users will leave that blank.  "N/A" is short and sweet, and doesn't look too out-of-place if you leave the field unset.

2. Additionally, go ahead and leave the Firmware Revision at "N/A" as well, rather than "1.0". For much the same reasons mentioned above, "N/A" is a better default if we don't know what the Firmware is.  If you don't like seeing the N/A, I'd welcome another pull request that adds the Firmware Revision as a field in the UI, following the same template you've set up for the Serial Number.

Otherwise, I think this looks great.  Once my two issues are fixed I don't see why this can't be merged.  Thanks for taking the time to work on this!

**Comment by iSteve-O** [comment]
I made the changes but I can't get the firmware to show in the home app or config UI accessory. I did exactly the same with it that I did with SN. maybe it doesn't work the same. I need to do a little more research on this. You can see the main branch in my fork is updated with it. it's running on my pi right now. Still showing 1.0 even though 1.0 isn't anywhere in the config or platform.ts anymore. I have deleted the cached accessory and everything I know. I need to go to sleep and mess with it with fresh eyes.

**Comment by iSteve-O** [comment]
@electroflame I did the updates you requested to merge this. Now anything that isn't set in the config will be `N/A` like you wanted. This works perfectly for me so I don't mind. This is tested working on my pi. When I had the issue yesterday I forgot to run build LOL (I was messing with another .js plugin that doesn't require that and just forgot) I also updated the readme with the new fields and the new 'hb-shell' method of install. Let me know if anything else, but this is good now. I believe it can be merged without issue. Thanks for taking the time.

**Comment by electroflame** [comment]
Looks good to me, thanks for working on this!

I'll get it updated on NPM soon, too.

**Comment by electroflame** [comment]
Just a quick update, this should be up on NPM now as well.

**Pull request merged**
